name: ocr_app
description: "A new Flutter project."
# Prevents the package from being accidentally published to pub.dev
# This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  fluttertoast: ^8.2.8
  get_it: ^8.0.0
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.4
  flutter_spinkit: ^5.2.1
  google_mlkit_text_recognition: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, uncomment and add an assets section:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, uncomment and add a fonts section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
